(define-record-type :cpscm__trampoline (cpscm__trampoline-create thunk) cpscm__trampoline? (text cpscm__trampoline-text cpscm__trampoline-set-text!) (thunk cpscm__trampoline-thunk))
(define-syntax cpscm__trampoline (syntax-rules () ((_ . rest) (let ((tr (cpscm__trampoline-create (lambda () . rest)))) (cpscm__trampoline-set-text! tr (quote rest)) tr))))
(define (cpscm__reduce-trampoline cc) (if (cpscm__trampoline? cc) 
(begin 
; (display "Executing: ") (pretty-print (cpscm__trampoline-text cc)) (newline) 
(cpscm__reduce-trampoline ((cpscm__trampoline-thunk cc)))) cc))
(define (cpscm_20_boolean->combinator k test) (k (if test (lambda (kk then else) (then kk)) (lambda (kk then else) (else kk)))))
(define cpscm* (lambda (k . args) (k (apply * args))))
(define cpscm+ (lambda (k . args) (k (apply + args))))
(define cpscm- (lambda (k . args) (k (apply - args))))
(define cpscm/ (lambda (k . args) (k (apply / args))))
(define cpscm< (lambda (k . args) (k (apply < args))))
(define cpscm<= (lambda (k . args) (k (apply <= args))))
(define cpscm= (lambda (k . args) (k (apply = args))))
(define cpscm> (lambda (k . args) (k (apply > args))))
(define cpscm>= (lambda (k . args) (k (apply >= args))))
(define cpscmabs (lambda (k . args) (k (apply abs args))))
(define cpscmacos (lambda (k . args) (k (apply acos args))))
(define cpscmangle (lambda (k . args) (k (apply angle args))))
(define cpscmappend (lambda (k . args) (k (apply append args))))
(define cpscmasin (lambda (k . args) (k (apply asin args))))
(define cpscmassoc (lambda (k . args) (k (apply assoc args))))
(define cpscmassq (lambda (k . args) (k (apply assq args))))
(define cpscmassv (lambda (k . args) (k (apply assv args))))
(define cpscmatan (lambda (k . args) (k (apply atan args))))
(define cpscmcaar (lambda (k . args) (k (apply caar args))))
(define cpscmcadr (lambda (k . args) (k (apply cadr args))))
(define cpscmcall-with-input-file (lambda (k . args) (k (apply call-with-input-file args))))
(define cpscmcall-with-output-file (lambda (k . args) (k (apply call-with-output-file args))))
(define cpscmcar (lambda (k . args) (k (apply car args))))
(define cpscmcdddar (lambda (k . args) (k (apply cdddar args))))
(define cpscmcddddr (lambda (k . args) (k (apply cddddr args))))
(define cpscmcdr (lambda (k . args) (k (apply cdr args))))
(define cpscmceiling (lambda (k . args) (k (apply ceiling args))))
(define cpscmchar->integer (lambda (k . args) (k (apply char->integer args))))
(define cpscmchar-alphabetic? (lambda (k . args) (k (apply char-alphabetic? args))))
(define cpscmchar-ci<=? (lambda (k . args) (k (apply char-ci<=? args))))
(define cpscmchar-ci<? (lambda (k . args) (k (apply char-ci<? args))))
(define cpscmchar-ci=? (lambda (k . args) (k (apply char-ci=? args))))
(define cpscmchar-ci>=? (lambda (k . args) (k (apply char-ci>=? args))))
(define cpscmchar-ci>? (lambda (k . args) (k (apply char-ci>? args))))
(define cpscmchar-downcase (lambda (k . args) (k (apply char-downcase args))))
(define cpscmchar-lower-case? (lambda (k . args) (k (apply char-lower-case? args))))
(define cpscmchar-numeric? (lambda (k . args) (k (apply char-numeric? args))))
(define cpscmchar-ready? (lambda (k . args) (k (apply char-ready? args))))
(define cpscmchar-upcase (lambda (k . args) (k (apply char-upcase args))))
(define cpscmchar-upper-case? (lambda (k . args) (k (apply char-upper-case? args))))
(define cpscmchar-whitespace? (lambda (k . args) (k (apply char-whitespace? args))))
(define cpscmchar<=? (lambda (k . args) (k (apply char<=? args))))
(define cpscmchar<? (lambda (k . args) (k (apply char<? args))))
(define cpscmchar=? (lambda (k . args) (k (apply char=? args))))
(define cpscmchar>=? (lambda (k . args) (k (apply char>=? args))))
(define cpscmchar>? (lambda (k . args) (k (apply char>? args))))
(define cpscmclose-input-port (lambda (k . args) (k (apply close-input-port args))))
(define cpscmclose-output-port (lambda (k . args) (k (apply close-output-port args))))
(define cpscmcomplex? (lambda (k . args) (k (apply complex? args))))
(define cpscmcons (lambda (k . args) (k (apply cons args))))
(define cpscmcos (lambda (k . args) (k (apply cos args))))
(define cpscmcurrent-input-port (lambda (k . args) (k (apply current-input-port args))))
(define cpscmcurrent-output-port (lambda (k . args) (k (apply current-output-port args))))
(define cpscmdenominator (lambda (k . args) (k (apply denominator args))))
(define cpscmdisplay (lambda (k . args) (k (apply display args))))
(define cpscmeof-object? (lambda (k . args) (k (apply eof-object? args))))
(define cpscmeq? (lambda (k . args) (k (apply eq? args))))
(define cpscmequal? (lambda (k . args) (k (apply equal? args))))
(define cpscmeqv? (lambda (k . args) (k (apply eqv? args))))
(define cpscmeval (lambda (k . args) (k (apply eval args))))
(define cpscmeven? (lambda (k . args) (k (apply even? args))))
(define cpscmexact->inexact (lambda (k . args) (k (apply exact->inexact args))))
(define cpscmexact? (lambda (k . args) (k (apply exact? args))))
(define cpscmexp (lambda (k . args) (k (apply exp args))))
(define cpscmexpt (lambda (k . args) (k (apply expt args))))
(define cpscmfloor (lambda (k . args) (k (apply floor args))))
(define cpscmfor-each (lambda (k . args) (k (apply for-each args))))
(define cpscmforce (lambda (k . args) (k (apply force args))))
(define cpscmgcd (lambda (k . args) (k (apply gcd args))))
(define cpscmimag-part (lambda (k . args) (k (apply imag-part args))))
(define cpscminexact->exact (lambda (k . args) (k (apply inexact->exact args))))
(define cpscminexact? (lambda (k . args) (k (apply inexact? args))))
(define cpscminput-port? (lambda (k . args) (k (apply input-port? args))))
(define cpscminteger->char (lambda (k . args) (k (apply integer->char args))))
(define cpscminteger? (lambda (k . args) (k (apply integer? args))))
(define cpscminteraction-environment (lambda (k . args) (k (apply interaction-environment args))))
(define cpscmlcm (lambda (k . args) (k (apply lcm args))))
(define cpscmlength (lambda (k . args) (k (apply length args))))
(define cpscmlist (lambda (k . args) (k (apply list args))))
(define cpscmlist->string (lambda (k . args) (k (apply list->string args))))
(define cpscmlist->vector (lambda (k . args) (k (apply list->vector args))))
(define cpscmlist-ref (lambda (k . args) (k (apply list-ref args))))
(define cpscmlist-tail (lambda (k . args) (k (apply list-tail args))))
(define cpscmlist? (lambda (k . args) (k (apply list? args))))
(define cpscmload (lambda (k . args) (k (apply load args))))
(define cpscmlog (lambda (k . args) (k (apply log args))))
(define cpscmmagnitude (lambda (k . args) (k (apply magnitude args))))
(define cpscmmake-polar (lambda (k . args) (k (apply make-polar args))))
(define cpscmmake-rectangular (lambda (k . args) (k (apply make-rectangular args))))
(define cpscmmake-string (lambda (k . args) (k (apply make-string args))))
(define cpscmmake-vector (lambda (k . args) (k (apply make-vector args))))
(define cpscmmap (lambda (k . args) (k (apply map args))))
(define cpscmmax (lambda (k . args) (k (apply max args))))
(define cpscmmember (lambda (k . args) (k (apply member args))))
(define cpscmmemq (lambda (k . args) (k (apply memq args))))
(define cpscmmemv (lambda (k . args) (k (apply memv args))))
(define cpscmmin (lambda (k . args) (k (apply min args))))
(define cpscmmodulo (lambda (k . args) (k (apply modulo args))))
(define cpscmnegative? (lambda (k . args) (k (apply negative? args))))
(define cpscmnewline (lambda (k . args) (k (apply newline args))))
(define cpscmnot (lambda (k . args) (k (apply not args))))
(define cpscmnull-environment (lambda (k . args) (k (apply null-environment args))))
(define cpscmnull? (lambda (k . args) (k (apply null? args))))
(define cpscmnumber->string (lambda (k . args) (k (apply number->string args))))
(define cpscmnumerator (lambda (k . args) (k (apply numerator args))))
(define cpscmodd? (lambda (k . args) (k (apply odd? args))))
(define cpscmopen-input-file (lambda (k . args) (k (apply open-input-file args))))
(define cpscmopen-output-file (lambda (k . args) (k (apply open-output-file args))))
(define cpscmoutput-port? (lambda (k . args) (k (apply output-port? args))))
(define cpscmpeek-char (lambda (k . args) (k (apply peek-char args))))
(define cpscmpositive? (lambda (k . args) (k (apply positive? args))))
(define cpscmquotient (lambda (k . args) (k (apply quotient args))))
(define cpscmrational? (lambda (k . args) (k (apply rational? args))))
(define cpscmrationalize (lambda (k . args) (k (apply rationalize args))))
(define cpscmread (lambda (k . args) (k (apply read args))))
(define cpscmread-char (lambda (k . args) (k (apply read-char args))))
(define cpscmreal-part (lambda (k . args) (k (apply real-part args))))
(define cpscmreal? (lambda (k . args) (k (apply real? args))))
(define cpscmremainder (lambda (k . args) (k (apply remainder args))))
(define cpscmreverse (lambda (k . args) (k (apply reverse args))))
(define cpscmround (lambda (k . args) (k (apply round args))))
(define cpscmscheme-report-environment (lambda (k . args) (k (apply scheme-report-environment args))))
(define cpscmset-car! (lambda (k . args) (k (apply set-car! args))))
(define cpscmset-cdr! (lambda (k . args) (k (apply set-cdr! args))))
(define cpscmsin (lambda (k . args) (k (apply sin args))))
(define cpscmsqrt (lambda (k . args) (k (apply sqrt args))))
(define cpscmstring (lambda (k . args) (k (apply string args))))
(define cpscmstring->list (lambda (k . args) (k (apply string->list args))))
(define cpscmstring->number (lambda (k . args) (k (apply string->number args))))
(define cpscmstring->symbol (lambda (k . args) (k (apply string->symbol args))))
(define cpscmstring-append (lambda (k . args) (k (apply string-append args))))
(define cpscmstring-ci<=? (lambda (k . args) (k (apply string-ci<=? args))))
(define cpscmstring-ci<? (lambda (k . args) (k (apply string-ci<? args))))
(define cpscmstring-ci=? (lambda (k . args) (k (apply string-ci=? args))))
(define cpscmstring-ci>=? (lambda (k . args) (k (apply string-ci>=? args))))
(define cpscmstring-ci>? (lambda (k . args) (k (apply string-ci>? args))))
(define cpscmstring-copy (lambda (k . args) (k (apply string-copy args))))
(define cpscmstring-fill! (lambda (k . args) (k (apply string-fill! args))))
(define cpscmstring-length (lambda (k . args) (k (apply string-length args))))
(define cpscmstring-ref (lambda (k . args) (k (apply string-ref args))))
(define cpscmstring-set! (lambda (k . args) (k (apply string-set! args))))
(define cpscmstring<=? (lambda (k . args) (k (apply string<=? args))))
(define cpscmstring<? (lambda (k . args) (k (apply string<? args))))
(define cpscmstring=? (lambda (k . args) (k (apply string=? args))))
(define cpscmstring>=? (lambda (k . args) (k (apply string>=? args))))
(define cpscmstring>? (lambda (k . args) (k (apply string>? args))))
(define cpscmsubstring (lambda (k . args) (k (apply substring args))))
(define cpscmsymbol->string (lambda (k . args) (k (apply symbol->string args))))
(define cpscmtan (lambda (k . args) (k (apply tan args))))
(define cpscmtranscript-off (lambda (k . args) (k (apply transcript-off args))))
(define cpscmtranscript-on (lambda (k . args) (k (apply transcript-on args))))
(define cpscmtruncate (lambda (k . args) (k (apply truncate args))))
(define cpscmvector (lambda (k . args) (k (apply vector args))))
(define cpscmvector->list (lambda (k . args) (k (apply vector->list args))))
(define cpscmvector-fill! (lambda (k . args) (k (apply vector-fill! args))))
(define cpscmvector-length (lambda (k . args) (k (apply vector-length args))))
(define cpscmvector-ref (lambda (k . args) (k (apply vector-ref args))))
(define cpscmvector-set! (lambda (k . args) (k (apply vector-set! args))))
(define cpscmwith-input-from-file (lambda (k . args) (k (apply with-input-from-file args))))
(define cpscmwith-output-to-file (lambda (k . args) (k (apply with-output-to-file args))))
(define cpscmwrite (lambda (k . args) (k (apply write args))))
(define cpscmwrite-char (lambda (k . args) (k (apply write-char args))))
(define cpscmzero? (lambda (k . args) (k (apply zero? args))))
(define cpscmboolean? (lambda (k . args) (k (apply boolean? args))))
(define cpscmchar? (lambda (k . args) (k (apply char? args))))
(define cpscmnumber? (lambda (k . args) (k (apply number? args))))
(define cpscmpair? (lambda (k . args) (k (apply pair? args))))
(define cpscmport? (lambda (k . args) (k (apply port? args))))
(define cpscmprocedure? (lambda (k . args) (k (apply procedure? args))))
(define cpscmstring? (lambda (k . args) (k (apply string? args))))
(define cpscmsymbol? (lambda (k . args) (k (apply symbol? args))))
(define cpscmvector? (lambda (k . args) (k (apply vector? args))))
(define cpscmcall-with-current-continuation (lambda (cpscmk cpscmf) (cpscm__trampoline ((lambda (cpscmccwinders) (cpscm__trampoline (begin (cpscm__reduce-trampoline ((lambda (g:ccwinders:208) (cpscm__trampoline (set! cpscmccwinders g:ccwinders:208))) cpscm__winders)) (cpscm__reduce-trampoline (cpscmf cpscmk (lambda (cpscm_ . cpscmxs) (cpscm__trampoline (cpscm__switch-winders (lambda (cpscm_) (cpscm__trampoline (apply cpscmk cpscmxs))) cpscmccwinders)))))))) (quote undefined)))))
(define cpscmcall-with-values (lambda (cpscmk cpscmproducer cpscmconsummer) (cpscm__trampoline (cpscmproducer (lambda cpscmvals (cpscm__trampoline (cpscmapply cpscmk cpscmconsummer cpscmvals)))))))
(define cpscmvalues (lambda (cpscmk . cpscmthings) (cpscm__trampoline (apply cpscmk cpscmthings))))
(define cpscm__winders (quote ()))
(define cpscm__switch-winders (lambda (g:k1 cpscm_ccwinders_41) (cpscm__trampoline ((lambda (cpscm_switch_42 cpscm_loop_43) (cpscm__trampoline ((lambda (g:k10 cpscm_switch_42_tmp cpscm_loop_43_tmp) (cpscm__trampoline (begin (cpscm__reduce-trampoline (set! cpscm_switch_42 cpscm_switch_42_tmp)) (cpscm__reduce-trampoline (g:k10 (set! cpscm_loop_43 cpscm_loop_43_tmp)))))) (lambda (g5) (cpscm__trampoline (cpscmreverse (lambda (g:ret-reverse:7) (cpscm__trampoline (cpscmreverse (lambda (g:ret-reverse:8) (cpscm__trampoline (cpscm_loop_43 g:k1 g:ret-reverse:7 g:ret-reverse:8))) cpscm_ccwinders_41))) cpscm__winders))) (lambda (g:k14 cpscm_a_44 cpscm_b_45) (cpscm__trampoline ((lambda (cpscm_run-all_46) (cpscm__trampoline ((lambda (g:k25 cpscm_run-all_46_tmp) (cpscm__trampoline (g:k25 (set! cpscm_run-all_46 cpscm_run-all_46_tmp)))) (lambda (g18) (cpscm__trampoline (cpscmmap (lambda (g:ret-map:21) (cpscm__trampoline (cpscmmap (lambda (g:ret-map:22) (cpscm__trampoline (cpscmappend-reverse! (lambda (g:ret-append-reverse!:20) (cpscm__trampoline (cpscm_run-all_46 (lambda (g:ret-_run-all_46:19) (cpscm__trampoline (g:k14 (set! cpscm__winders cpscm_ccwinders_41)))) g:ret-append-reverse!:20))) g:ret-map:21 g:ret-map:22))) cpscmcar cpscm_b_45))) cpscmcdr cpscm_a_44))) (lambda (g:k28 cpscm_to-apply_47) (cpscm__trampoline (cpscmnull? (lambda (g:ret-null?:31) (cpscm__trampoline (cpscm_20_boolean->combinator (lambda (g:ret-_20_boolean->combinator:30) (cpscm__trampoline (cpscmapply g:k28 g:ret-_20_boolean->combinator:30 (lambda (g:k33) (cpscm__trampoline (g:k33 #t))) (lambda (g:k35) (cpscm__trampoline (cpscmcar (lambda (g:ret-car:37) (cpscm__trampoline (cpscmapply g:k35 g:ret-car:37 (quote ())))) cpscm_to-apply_47))) (quote ())))) g:ret-null?:31))) cpscm_to-apply_47)))))) (quote undefined)))) (lambda (g:k39 cpscm_a_44 cpscm_b_45) (cpscm__trampoline (cpscmnull? (lambda (g:ret-null?:43) (cpscm__trampoline ((lambda (g:k53) (cpscm__trampoline (cpscm_20_boolean->combinator (lambda (g:ret-_20_boolean->combinator:55) (cpscm__trampoline (cpscmapply g:k53 g:ret-_20_boolean->combinator:55 (lambda (g:k57) (cpscm__trampoline (g:k57 g:ret-null?:43))) (lambda (g:k59) (cpscm__trampoline (cpscmnull? (lambda (g:ret-null?:61) (cpscm__trampoline (cpscm_20_boolean->combinator (lambda (g:ret-_20_boolean->combinator:65) (cpscm__trampoline (cpscmapply g:k59 g:ret-_20_boolean->combinator:65 (lambda (g:k67) (cpscm__trampoline (g:k67 g:ret-null?:61))) (lambda (g:k69) (cpscm__trampoline (cpscmcar (lambda (g:ret-car:72) (cpscm__trampoline (cpscmcar (lambda (g:ret-car:73) (cpscm__trampoline (cpscmeq? (lambda (g:ret-eq?:71) (cpscm__trampoline (cpscmnot g:k69 g:ret-eq?:71))) g:ret-car:72 g:ret-car:73))) cpscm_b_45))) cpscm_a_44))) (quote ())))) g:ret-null?:61))) cpscm_b_45))) (quote ())))) g:ret-null?:43))) (lambda (g42) (cpscm__trampoline (cpscm_20_boolean->combinator (lambda (g:ret-_20_boolean->combinator:41) (cpscm__trampoline (cpscmapply g:k39 g:ret-_20_boolean->combinator:41 (lambda (g:k45) (cpscm__trampoline (cpscm_switch_42 g:k45 cpscm_a_44 cpscm_b_45))) (lambda (g:k48) (cpscm__trampoline (cpscmcdr (lambda (g:ret-cdr:50) (cpscm__trampoline (cpscmcdr (lambda (g:ret-cdr:51) (cpscm__trampoline (cpscm_loop_43 g:k48 g:ret-cdr:50 g:ret-cdr:51))) cpscm_b_45))) cpscm_a_44))) (quote ())))) g42)))))) cpscm_a_44)))))) (quote undefined) (quote undefined)))))
(define cpscmdynamic-wind (lambda (g:k75 cpscm_before_41 cpscm_thunk_42 cpscm_after_43) (cpscm__trampoline ((lambda (cpscm_result_44) (cpscm__trampoline (begin (cpscm__reduce-trampoline (set! cpscm_result_44 #f)) (cpscm__reduce-trampoline (cpscm_before_41 (lambda (g:ret-_before_41:80) (cpscm__trampoline (cpscmcons (lambda (g:ret-cons:83) (cpscm__trampoline (cpscmcons (lambda (g:ret-cons:82) (cpscm__trampoline (begin (cpscm__reduce-trampoline (set! cpscm__winders g:ret-cons:82)) (cpscm__reduce-trampoline (cpscm_thunk_42 (lambda (g:ret-_thunk_42:85) (cpscm__trampoline (begin (cpscm__reduce-trampoline (set! cpscm_result_44 g:ret-_thunk_42:85)) (cpscm__reduce-trampoline (cpscmcdr (lambda (g:ret-cdr:87) (cpscm__trampoline (begin (cpscm__reduce-trampoline (set! cpscm__winders g:ret-cdr:87)) (cpscm__reduce-trampoline (cpscm_after_43 (lambda (g:ret-_after_43:88) (cpscm__trampoline (g:k75 cpscm_result_44)))))))) cpscm__winders)))))))))) g:ret-cons:83 cpscm__winders))) cpscm_before_41 cpscm_after_43)))))))) (quote undefined)))))
(define cpscmwith-failure-continuation (lambda (g:k90 cpscm_hnd_41 cpscm_thunk_42) (cpscm__trampoline ((lambda (cpscm_oldhnd_43) (cpscm__trampoline (begin (cpscm__reduce-trampoline (set! cpscm_oldhnd_43 #f)) (cpscm__reduce-trampoline (cpscmcall/cc g:k90 (lambda (g:k97 cpscm_cc_44) (cpscm__trampoline (cpscmdynamic-wind g:k97 (lambda (g:k100) (cpscm__trampoline (cpscmcurrent-error-handler (lambda (g:ret-current-error-handler:102) (cpscm__trampoline (g:k100 (set! cpscm_oldhnd_43 g:ret-current-error-handler:102))))))) (lambda (g:k104) (cpscm__trampoline (cpscmcurrent-error-handler (lambda (g:ret-current-error-handler:105) (cpscm__trampoline (cpscm_thunk_42 g:k104))) cpscm_hnd_41 cpscm_cc_44))) (lambda (g:k108) (cpscm__trampoline (cpscmcurrent-error-handler g:k108 cpscm_oldhnd_43))))))))))) (quote undefined)))))
(define cpscmwith/fc cpscmwith-failure-continuation)
(define cpscmappend! cpscmappend)
(define cpscmappend-reverse (lambda (g:k111 cpscm_rev-head_41 cpscm_tail_42) (cpscm__trampoline (cpscmreverse (lambda (g:ret-reverse:113) (cpscm__trampoline (cpscmappend g:k111 g:ret-reverse:113 cpscm_tail_42))) cpscm_rev-head_41))))
(define cpscmappend-reverse! cpscmappend-reverse)
(define cpscmreverse! cpscmreverse)
(define cpscmmap (lambda (g:k115 cpscm_f_41 cpscm_l_42) (cpscm__trampoline ((lambda (cpscm_loop_43) (cpscm__trampoline ((lambda (g:k122 cpscm_loop_43_tmp) (cpscm__trampoline (g:k122 (set! cpscm_loop_43 cpscm_loop_43_tmp)))) (lambda (g119) (cpscm__trampoline (cpscm_loop_43 g:k115 cpscm_l_42 (quote ())))) (lambda (g:k125 cpscm_l_44 cpscm_res_45) (cpscm__trampoline (cpscmnull? (lambda (g:ret-null?:128) (cpscm__trampoline (cpscm_20_boolean->combinator (lambda (g:ret-_20_boolean->combinator:127) (cpscm__trampoline (cpscmapply g:k125 g:ret-_20_boolean->combinator:127 (lambda (g:k130) (cpscm__trampoline (cpscmreverse! g:k130 cpscm_res_45))) (lambda (g:k133) (cpscm__trampoline (cpscmcdr (lambda (g:ret-cdr:135) (cpscm__trampoline (cpscmcar (lambda (g:ret-car:138) (cpscm__trampoline (cpscm_f_41 (lambda (g:ret-_f_41:137) (cpscm__trampoline (cpscmcons (lambda (g:ret-cons:136) (cpscm__trampoline (cpscm_loop_43 g:k133 g:ret-cdr:135 g:ret-cons:136))) g:ret-_f_41:137 cpscm_res_45))) g:ret-car:138))) cpscm_l_44))) cpscm_l_44))) (quote ())))) g:ret-null?:128))) cpscm_l_44)))))) (quote undefined)))))
(define cpscmfor-each (lambda (g:k140 cpscm_k_41 cpscm_f_42 cpscm_l_43) (cpscm__trampoline ((lambda (cpscm_loop_44) (cpscm__trampoline ((lambda (g:k147 cpscm_loop_44_tmp) (cpscm__trampoline (g:k147 (set! cpscm_loop_44 cpscm_loop_44_tmp)))) (lambda (g144) (cpscm__trampoline (cpscm_loop_44 g:k140 cpscm_l_43 (quote ())))) (lambda (g:k150 cpscm_l_45) (cpscm__trampoline (cpscmnull? (lambda (g:ret-null?:153) (cpscm__trampoline (cpscm_20_boolean->combinator (lambda (g:ret-_20_boolean->combinator:152) (cpscm__trampoline (cpscmapply g:k150 g:ret-_20_boolean->combinator:152 (lambda (g:k155) (cpscm__trampoline (g:k155 #t))) (lambda (g:k157) (cpscm__trampoline (cpscmcar (lambda (g:ret-car:159) (cpscm__trampoline (cpscm_f_42 g:k157 g:ret-car:159))) cpscm_l_45))) (quote ())))) g:ret-null?:153))) cpscm_l_45)))))) (quote undefined)))))
(define cpscmassoc (lambda (g:k161 cpscm_x_41 cpscm_lis_42 . cpscm_maybe-=_43) (cpscm__trampoline (cpscmnull? (lambda (g:ret-null?:165) (cpscm__trampoline (cpscm_20_boolean->combinator (lambda (g:ret-_20_boolean->combinator:164) (cpscm__trampoline (cpscmapply (lambda (g:ret-apply:163) (cpscm__trampoline (cpscmfind g:k161 (lambda (g:k170 cpscm_entry_45) (cpscm__trampoline (cpscmcar (lambda (g:ret-car:172) (cpscm__trampoline (g:ret-apply:163 g:k170 cpscm_x_41 g:ret-car:172))) cpscm_entry_45))) cpscm_lis_42))) g:ret-_20_boolean->combinator:164 (lambda (g:k174) (cpscm__trampoline (g:k174 cpscmequal?))) (lambda (g:k176) (cpscm__trampoline (cpscmcar g:k176 cpscm_maybe-=_43))) (quote ())))) g:ret-null?:165))) cpscm_maybe-=_43))))
(define cpscmassq (lambda (g:k179 cpscm_x_41 cpscm_l_42) (cpscm__trampoline (cpscmassoc g:k179 cpscm_x_41 cpscm_l_42 cpscmeq?))))
(define cpscmassv (lambda (g:k182 cpscm_x_41 cpscm_l_42) (cpscm__trampoline (cpscmassoc g:k182 cpscm_x_41 cpscm_l_42 cpscmeqv?))))
(define cpscmmember (lambda (g:k185 cpscm_x_41 cpscm_lis_42 . cpscm_maybe-=_43) (cpscm__trampoline (cpscmnull? (lambda (g:ret-null?:189) (cpscm__trampoline (cpscm_20_boolean->combinator (lambda (g:ret-_20_boolean->combinator:188) (cpscm__trampoline (cpscmapply (lambda (g:ret-apply:187) (cpscm__trampoline (cpscmfind-tail g:k185 (lambda (g:k194 cpscm_y_45) (cpscm__trampoline (g:ret-apply:187 g:k194 cpscm_x_41 cpscm_y_45))) cpscm_lis_42))) g:ret-_20_boolean->combinator:188 (lambda (g:k197) (cpscm__trampoline (g:k197 cpscmequal?))) (lambda (g:k199) (cpscm__trampoline (cpscmcar g:k199 cpscm_maybe-=_43))) (quote ())))) g:ret-null?:189))) cpscm_maybe-=_43))))
(define cpscmmemq (lambda (g:k202 cpscm_x_41 cpscm_l_42) (cpscm__trampoline (cpscmmember g:k202 cpscm_x_41 cpscm_l_42 cpscmeq?))))
(define cpscmmemv (lambda (g:k205 cpscm_x_41 cpscm_l_42) (cpscm__trampoline (cpscmmember g:k205 cpscm_x_41 cpscm_l_42 cpscmeqv?))))
(define cpscmcall/cc cpscmcall-with-current-continuation)
